// <auto-generated />
namespace JobBoardTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MixingSomething : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MixingSomething));
        
        string IMigrationMetadata.Id
        {
            get { return "202106091626318_MixingSomething"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
