// <auto-generated />
namespace JobBoardTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DropProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "202106021758080_DropProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
